# frozen_string_literal: true

require "date"
require "fileutils"
require "tap"
require "utils/path"
require_relative "autoupdate/cleanup"
require_relative "autoupdate/core"
require_relative "autoupdate/delete"
require_relative "autoupdate/interval"
require_relative "autoupdate/notify"
require_relative "autoupdate/start"
require_relative "autoupdate/status"
require_relative "autoupdate/stop"
require_relative "autoupdate/version"
require_relative "autoupdate/logs"
