require "fileutils"
require "pathname"
require "autoupdate/core"
require "autoupdate/cleanup"
require "autoupdate/delete"
require "autoupdate/start"
require "autoupdate/stop"
require "autoupdate/version"
