name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - run: ruby test/interval_test.rb

      - run: brew style "$GITHUB_REPOSITORY"
