name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run tests
        run: |
          for test in test/*_test.rb; do
            ruby "$test"
          done

      - run: brew style "$GITHUB_REPOSITORY"
